"""add payment_method to transactions and create daily_financial_summaries

Revision ID: aee85a9f740b
Revises: 6dc48c410ab0
Create Date: 2026-08-29 23:08:19.631891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee85a9f740b'
down_revision = '6dc48c410ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_financial_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('renewals_count', sa.Integer(), nullable=False),
    sa.Column('total_renewals_amount', sa.Integer(), nullable=False),
    sa.Column('payments_count', sa.Integer(), nullable=False),
    sa.Column('cash_received', sa.Integer(), nullable=False),
    sa.Column('electronic_received', sa.Integer(), nullable=False),
    sa.Column('total_collected', sa.Integer(), nullable=False),
    sa.Column('total_transactions_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_date', 'admin_id', name='uq_summary_date_admin')
    )
    with op.batch_alter_table('daily_financial_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_financial_summaries_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_financial_summaries_summary_date'), ['summary_date'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('daily_financial_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_financial_summaries_summary_date'))
        batch_op.drop_index(batch_op.f('ix_daily_financial_summaries_admin_id'))

    op.drop_table('daily_financial_summaries')
    # ### end Alembic commands ###
